# Generated by Django 5.0.6 on 2024-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('sofa', 'Sofa'), ('recliner', 'Recliner'), ('dining', 'Dining'), ('bed', 'Bed'), ('office_study_table', 'Office & Study Table'), ('chair', 'Chair'), ('center_table', 'Center Table'), ('office_chair', 'Office Chair')], max_length=50),
        ),
    ]
