# Generated by Django 5.0.6 on 2024-11-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_cart', '0008_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_entries', to='e_cart.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
